### PR TITLE
Improve c# compatibility

### PR DESCRIPTION
**Pull request by wallymathieu**

### CODE REVIEW

**Comment by panesofglass** [comment]
@wallymathieu, this is excellent! Sorry, I only just saw the PR. Any idea as to why the build is failing?

**Comment by panesofglass** [comment]
Seems the build failure may be unrelated to the changes.

**Comment by wallymathieu** [comment]
perhaps a need to update the template with new paket and FAKE

**Comment by panesofglass** [comment]
@forki any ideas about the build issue?

**Comment by wallymathieu** [comment]
I'm trying out some changes in order to make it nicer to use in c#. https://github.com/wallymathieu/FSharpPlus.CSharp

FSharpChoice works better as Choices
FSharpOption is nicer as Options ...

**Comment by panesofglass** [comment]
@wallymathieu any updates, or would you like me to merge?

**Comment by wallymathieu** [comment]
Fixing the build error would probably be a separate pull request.

**Pull request merged**
