### PR TITLE
Add `sequence_` and `mapM_` to Validation

### PR DESCRIPTION
**Pull request by semyon2105**

### CODE REVIEW

**Comment by panesofglass** [comment]
Is the `_` suffix sufficiently clear? Might this be better with a `choose` prefix?

**Comment by semyon2105** [comment]
The underscore here basically means "ignore". AFAIK it's a common convention in F# and Haskell to use an underscore suffix in function names that represent the "value ignored" versions of such functions. The alternative names I can think of are `mapMIgnore` and `sequenceIgnore`

I don't see how renaming this function to `chooseM` is appropriate in this case. `mapM_`'s semantics is the same as in `mapM`. It's just that the possible success value will be dropped and we'll have `unit` instead.

**Comment by panesofglass** [comment]
I've typically seen the `_` suffix used with lenses and optics, so that's probably what led to my confusion. I think using `Ignore` as a suffix would be clearer. Do you mind making that change?

**Comment by semyon2105** [comment]
Renamed the functions

**Comment by gdziadkiewicz** [comment]
@semyon2105 Thanks for the contribution!

**Pull request merged**
