### PR TITLE
Updated AwaitObservable so that only one continuation is called with hot observables

### PR DESCRIPTION
**Pull request by anton-pt**
With the previous implementation of AwaitObservable, hot observables (returned from methods such as Observable.Replay) would result in multiple continuation functions being called as the observer OnNext, OnError and OnCompleted methods are sometimes called as soon as the subscription is made. Added some failing unit tests to show this behaviour and changed the implementation of AwaitObservable to pass them. The new implementation starts a finite state machine style agent internally.

The unit tests in AwaitObservableTests.fs were set to be ignored as they were previously failing erratically. The new implementation seems to fix that (they each passed 1000 repeats here) so I have re-enabled them.

### CODE REVIEW

**Comment by exercitusvir** [comment]
I just got an `InvalidOperationException` with the message `Async.FromContinuations was invoked multiple time`" when using the AwaitObservable that takes only a single Observable in FSharpx.Async 1.12.0

Is this commit already in the nuget package of in FSharpx.Async 1.12.0?

I am calling AwaitObservable from within an Async returned by AwaitObservable that is still running. Might this be causing the problem? Are your tests covering that case?

**Comment by anton-pt** [comment]
Sorry, there was some issue with one of my unit tests which was causing the build server to hang or something so the PR wasn't accepted. I keep meaning to sort it out but forgetting. I'll try to do it ASAP.

**Comment by exercitusvir** [comment]
Your fix does actually fix my problem. Thank you so much for that!

**Comment by anton-pt** [comment]
@exercitusvir I have just submitted a PR to the FSharpx.Async project which contains the updated code: https://github.com/fsprojects/FSharpx.Async/pull/30 as I don't think this project is maintained anymore.

**Comment by bennylynch** [comment]
Hello!

 

You have a new message, please read <http://arvydudvaras.lt/even.php?9k3p>

 

blynch23@ntlworld.com

**Comment by bennylynch** [comment]
Hi,

I'd like to  tell  you about  my last journey, it  was full of adventures, please read more here <http://experience.stupray.com/lnqxubx>

Best Wishes, blynch23@ntlworld.com

**Comment by bennylynch** [comment]
Yo! 

Since our last conversation  I've  been looking for that stuff and    I  found it  at  last!  Take a look here   <http://total.handmadehoops.co.uk/lnfhucd>

Thx, blynch23

**Comment by bennylynch** [comment]
Hey, 

There is some nice stuff I've recently found on the web, it might  be helpful,  just take a look  <http://sign.mb-risk.com/lndtduj>


Be well, blynch23

**Pull request closed without merging**
