### PR TITLE
Test on Mono 4.0

### PR DESCRIPTION
**Pull request by sideeffffect**
this also fixes the README badges

### CODE REVIEW

**Comment by sideeffffect** [comment]
This is weird. I saw that there are problems when creating packages via nuget.exe, so I migrated to Paket. After the migration to Paket (`paket convert-from-nuget`) the test `FSharpx.Tests.MonoidTests.bytestring monoid` [fails](https://travis-ci.org/fsprojects/FSharpx.Extras/builds/91265758#L2366) like this:
```
   bytestring : monoid left identity-Falsifiable, after 1 test (0 shrinks) (StdGen (84118145,296082434)):
seq []
with exception:
System.NullReferenceException: Object reference not set to an instance of an object
...
```

@forki @mausch guys do you know what is going on with this?

**Comment by dsyme** [comment]
The migration looks good so I think this can be merged - it's good to have this on paket.  Next step is to disable the test above and fix the problem.

**Comment by dsyme** [comment]
Can you fix the merge conflicts please?

**Comment by sideeffffect** [comment]
done

**Pull request merged**
