### PR TITLE
Faster and less-memory-consuming niceName

### PR DESCRIPTION
**Pull request by Thorium**
This makes niceName function a bit faster and consume less memory.

### CODE REVIEW

**Comment by Thorium** [comment]
Mac CI build-failure is not related to this commit.

This function has even more tweaked version in [here](
https://github.com/fsprojects/SQLProvider/blob/2fc34da40c4aa2beb7fe8dbc7eaccd5ac178ea2b/src/SQLProvider.Runtime/Utils.fs#L378), but that uses Spans which are not available in this project.

**Comment by gdziadkiewicz** [comment]
Hi, thanks for contributing! I will check it today 😄

**Comment by gdziadkiewicz** [comment]
Can you refresh with master? I fixed the macos failing build

**Comment by gdziadkiewicz** [comment]
Hi, I read through the code and am happy with it, but I still need to do one last check if the changes in `@?`, `LetterDigit`, `Upper`, and `Lower` are breaking for the current users.

**Comment by Thorium** [comment]
If they appear to be, there could easily be both internal and external versions of those functions.

**Comment by gdziadkiewicz** [comment]
Hi, I got a repro for the problematic situation: https://github.com/gdziadkiewicz/fsharpx-extras-binary-compatibility. I don't mind incrementing the major version, but please give me a moment to think about other breaking changes we could include during  the increment (do you have any ideas?)

**Comment by Thorium** [comment]
The reason I needed the optimization: In SQLProvider we use this function on intellisense on database, on every table, on every column. Databases can be big. And with intellisense, you expect that when you type a dot, the system reacts now and not a second later.

Just a tiny test on my laptop (after 4 warm-up runs on both):

```fsharp
open System
let someNames = [|"testThing"; "test3X"; "BIG"; "this_is_test"|] |> Array.replicate 500000 |> Array.concat
#time;;

// FSharpX.Extras Old:
someNames |> Array.map niceName;;
// Real: 00:00:01.240, CPU: 00:00:01.234, GC gen0: 16, gen1: 5, gen2: 1

// FSharpX.Extras New:
someNames |> Array.map niceName;;
// Real: 00:00:00.655, CPU: 00:00:00.296, GC gen0: 0, gen1: 0, gen2: 0
```

**Comment by gdziadkiewicz** [comment]
@Thorium If you add the ValueOption-based `satisfies` and active patterns as private code, then we can merge and release a new, quicker `niceName`  even today (sorry for the additional work!) with a patch.

As for the general move to `ValueOption` for API, I will create a separate issue and do it all at once with a major version bump

**Comment by Thorium** [comment]
This should be good now.

**Pull request merged**
