### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by panesofglass**
Addresses comments in #370 and issue #372 

cc @eriawan

### CODE REVIEW

**Comment by panesofglass** [comment]
My local build fails with:

```
C:\Code\FSharpx.Extras\.paket\Paket.Restore.targets(321,15): error MSB4064: The "BuildOutputFolders" parameter is not supported by the "PackTask" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Code\FSharpx.Extras\src\FSharpx.Extras\FSharpx.Extras.fsproj]                                                       C:\Code\FSharpx.Extras\.paket\Paket.Restore.targets(284,5): error MSB4063: The "PackTask" task could not be initialized with its input parameters.  [C:\Code\FSharpx.Extras\src\FSharpx.Extras\FSharpx.Extras.fsproj]                           Running build failed.                                                                                                   Error:                                                                                                                  System.Exception: Pack failed on "pack" "C:\Code\FSharpx.Extras\src\FSharpx.Extras\FSharpx.Extras.fsproj" --configuration Release --output C:\Code\FSharpx.Extras\bin --no-build                                                                   at Fake.DotNetCli.Pack@372-3.Invoke(String message) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 372         at Fake.DotNetCli.Pack(FSharpFunc`2 setPackParams) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 372          at FSI_0005.Build.clo@107-14.Invoke(String proj) in C:\Code\FSharpx.Extras\build.fsx:line 108                           at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)                         at FSI_0005.Build.clo@105-13.Invoke(Unit _arg6) in C:\Code\FSharpx.Extras\build.fsx:line 106                            at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 62
```

I think this is something to do with the outdated FAKE 4 `DotNetCli` module. We may need to update to FAKE 5 to get this to build.

**Comment by eriawan** [comment]
@panesofglass 

I agree. Looks like we have to update FAKE to FAKE 5.

**Comment by panesofglass** [comment]
I updated to FAKE 5, but it seems the problem is actually with the FSharpx.Tests project:

```
FSC : error FS2026: Deterministic builds only support portable PDBs (--debug:portable or --debug:embedded) [C:\Code\FSharpx.Extras\tests\FSharpx.Tests\FSharpx.Tests.fsproj]
```

**Comment by panesofglass** [comment]
Also, in updating to FAKE 5, I had to remove the generation of documentation, as I have no idea how to retain that in FAKE 5 and .NET Core. Any help is appreciated.

**Comment by eriawan** [comment]
Let me assess doc generation #378 first this weekend.

If it's quite trivial, I'll try to submit PR next week.

**Pull request merged**
