### PR TITLE
added try with expression for task monad.

### PR DESCRIPTION
**Pull request by AntyaDev**

### CODE REVIEW

**Comment by mausch** [comment]
Looks pretty good, thanks! Just one question: what happens if `catchFn` throws in [this line](https://github.com/AntyaDev/FSharpx.Extras/blob/25ecc9e942c10812eba7c15918be803c156281e9/src/FSharpx.Extras/ComputationExpressions/Monad.fs#L1028)?

**Comment by AntyaDev** [comment]
@mausch what you expect to happens?

**Comment by mausch** [comment]
My guess is it will throw losing the information from the original Task exception.

**Comment by AntyaDev** [comment]
can you please give me the simple example, maybe even in C# :)

**Comment by mausch** [comment]
Not sure what you mean... I'm only guessing here, just from reading the code. We obviously wouldn't want to lose the information from the original exception. Can you add a test to confirm this behavior?

**Comment by AntyaDev** [comment]
like this, for example?

```
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Test();
            }
            catch (Exception ex)
            {
                
            }
            
        }

        static void Test()
        {
            Task t = new Task(() => { throw new Exception(); });

            try
            {
                t.Start();
                t.Wait();
            }
            catch (AggregateException e)
            {
                throw new ArgumentException();
            }
        }
    }
```

**Comment by AntyaDev** [comment]
@mausch I think you meant rerise() exception? if yes, it's not possible at all, even for async { }

**Comment by AntyaDev** [comment]
@mausch what happens if catchFn throws in this line? yes of course you will lose original exception.

**Comment by AntyaDev** [comment]
@mausch you can write rerise() for async { } 
http://stackoverflow.com/questions/7168801/how-to-use-reraise-in-async-workflows-in-f

**Comment by AntyaDev** [comment]
any progress?

**Comment by AntyaDev** [comment]
any progress?

**Comment by mausch** [comment]
Merged, thanks!

**Comment by AntyaDev** [comment]
thanks!

**Pull request merged**
