### PR TITLE
Fix Travis and AppVeyor builds.

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
Link to AppVeyor build:  https://ci.appveyor.com/project/fsgit/fsharpx/builds/29323586

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
@sergey-tihon Can you do the same thing you did in FSharpx.Collections to restore the AppVeyor PR checks?

**Comment by sergey-tihon** [comment]
Done, I've created new AppVeyour project for this repo
https://ci.appveyor.com/project/sergey-tihon/fsharpx-extras

Master badge [Build status](https://ci.appveyor.com/project/sergey-tihon/fsharpx-extras/branch/master)

**Comment by gdziadkiewicz** [comment]
@panesofglass is it good to go?

**Comment by panesofglass** [comment]
Yes, and thank you both, @sergey-tihon and @gdziadkiewicz!

**Pull request merged**
