### PR TITLE
update FSharpx.Async to 1.14.1 and FSharpx.Collections to 2.0.0 in paket.lock

### PR DESCRIPTION
**Pull request by eriawan**
Update these dependencies: FSharpx.Async to 1.14.1 and FSharpx.Collections to 2.0.0 in paket.lock

### CODE REVIEW

**Comment by eriawan** [comment]
@panesofglass 

Related to issue #370 particularly this comment: https://github.com/fsprojects/FSharpx.Extras/issues/370#issuecomment-518284931
Could you please review?

**Comment by panesofglass** [comment]
Thank you, @eriawan!

**Comment by panesofglass** [comment]
Unfortunately, there are changes in the dependencies that make it more complicated than just updating versions.

**Comment by eriawan** [comment]
@panesofglass 
> Unfortunately, there are changes in the dependencies that make it more complicated than just updating versions.
Changes in dependencies? Please elaborate.

**Comment by panesofglass** [comment]
@eriawan, FSharp.Core 4.6.2 is now required. There were several other changes that popped up when I ran paket update on each of the dependencies mentioned in this issue, as well.

**Comment by eriawan** [comment]
@panesofglass 

Thanks for the update and the merge! I had tried to solve this myself but I was so confused myself.
Does this mean now FSharp.Async is ready to be released to nuget?

**Comment by panesofglass** [comment]
I don't know about the latter. Is there a link or PR to which you could point me?

**Comment by eriawan** [comment]
@panesofglass 

> I think FSharpx.Async should already be updated. Is something more needed?

Thanks for pointing that! 🙂 👍 
Yes, it has been updated. I was thinking and wondering before, that we should ensure FSharpx.Async be in sync with the one that we have now, including the necessary dependencies. After looking at the current state of FSharpx.Async, we are good. Apologize if I might add more confusion to you. 

Our FSharpx.Extras is in good condition again now.

**Pull request merged**
